/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class MenuPrincipal extends javax.swing.JFrame {
 
    
    public MenuPrincipal() {
        initComponents();      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMGestionCiudades = new javax.swing.JMenu();
        jGestionCiudades = new javax.swing.JMenuItem();
        jMGestionAlojamiento = new javax.swing.JMenuItem();
        jGestionPasaje = new javax.swing.JMenuItem();
        jGestionPaquetes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1000, 1000));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMinimumSize(new java.awt.Dimension(1000, 1000));
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 1000));

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMGestionCiudades.setText("Administracion");

        jGestionCiudades.setText("Gestion Ciudades");
        jGestionCiudades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGestionCiudadesMouseClicked(evt);
            }
        });
        jGestionCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGestionCiudadesActionPerformed(evt);
            }
        });
        jMGestionCiudades.add(jGestionCiudades);

        jMGestionAlojamiento.setText("Gestion Alojamiento");
        jMGestionAlojamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMGestionAlojamientoMouseClicked(evt);
            }
        });
        jMGestionAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGestionAlojamientoActionPerformed(evt);
            }
        });
        jMGestionCiudades.add(jMGestionAlojamiento);

        jGestionPasaje.setText("Gestion Pasaje");
        jGestionPasaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGestionPasajeMouseClicked(evt);
            }
        });
        jGestionPasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGestionPasajeActionPerformed(evt);
            }
        });
        jMGestionCiudades.add(jGestionPasaje);

        jMenuBar1.add(jMGestionCiudades);

        jGestionPaquetes.setText("Gestion Paquetes");
        jGestionPaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGestionPaquetesMouseClicked(evt);
            }
        });
        jGestionPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGestionPaquetesActionPerformed(evt);
            }
        });
        jMenuBar1.add(jGestionPaquetes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jGestionCiudadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGestionCiudadesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jGestionCiudadesMouseClicked

    private void jMGestionAlojamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMGestionAlojamientoMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jMGestionAlojamientoMouseClicked

    private void jGestionPasajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGestionPasajeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jGestionPasajeMouseClicked

    private void jGestionPaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGestionPaquetesMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        GestionPaquetes GPQ = new GestionPaquetes();
        GPQ.setVisible(true);  
        jDesktopPane1.add(GPQ);
        jDesktopPane1.moveToFront(GPQ);
    }//GEN-LAST:event_jGestionPaquetesMouseClicked

    private void jGestionPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGestionPaquetesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jGestionPaquetesActionPerformed

    private void jMGestionAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGestionAlojamientoActionPerformed
        // TODO add your handling code here:
       try{jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        GestionAlojamiento GA = new GestionAlojamiento();
        GA.setVisible(true);  
        jDesktopPane1.add(GA);
        jDesktopPane1.moveToFront(GA);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "error al cargar interfaz");
        }
    }//GEN-LAST:event_jMGestionAlojamientoActionPerformed

    private void jGestionCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGestionCiudadesActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        GestionCiudades GC = new GestionCiudades();
        GC.setVisible(true);  
        jDesktopPane1.add(GC);
        jDesktopPane1.moveToFront(GC);
    }//GEN-LAST:event_jGestionCiudadesActionPerformed

    private void jGestionPasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGestionPasajeActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        GestionPasaje GP = new GestionPasaje();
        GP.setVisible(true);  
        jDesktopPane1.add(GP);
        jDesktopPane1.moveToFront(GP);
    }//GEN-LAST:event_jGestionPasajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jGestionCiudades;
    private javax.swing.JMenu jGestionPaquetes;
    private javax.swing.JMenuItem jGestionPasaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMGestionAlojamiento;
    private javax.swing.JMenu jMGestionCiudades;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
